apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
 - ../../base

namespace: dev

namePrefix: 
  dev- 
patches:
 - path: replicas.yaml
images:
 - name : $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG