apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
 - ../../base

namespace: prod

namePrefix: 
  prod- 

patches:
 - path: replicas.yaml

images:
 - name : $DOCKER_ID/$DOCKER_IMAGE:$DOCKER_TAG