apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: dev

---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: staging


---

apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: prod
