apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (9d8dcb518)
    traefik.enable: "true"
    traefik.http.routers.fastapi.rule: Host(`fastapi.localhost`)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (9d8dcb518)
        traefik.enable: "true"
        traefik.http.routers.fastapi.rule: Host(`fastapi.localhost`)
      creationTimestamp: null
      labels:
        io.kompose.network/fastapi-docker-traefik-default: "true"
        io.kompose.service: web
    spec:
      containers:
        - args:
            - bash
            - -c
            - while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0
          env:
            - name: DATABASE_URL
              value: postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
          image: web
          name: web
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: web-claim0
      restartPolicy: Always
      volumes:
        - name: web-claim0
          persistentVolumeClaim:
            claimName: web-claim0
status: {}
